config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root to: "home#home"

  get '/learners/searchlocation', to: 'learners#searchlocation'
  get '/learners/allbookings', to: 'learners#allbookings'
  get '/learners/createbooking/:school_id', to: 'learners#createbooking'
  get '/instructors/allbookings', to: 'instructors#allbookings'
  get '/schools/allbookings', to: 'schools#allbookings'
  get '/schools/allinstructors', to: 'schools#allinstructors'
  get '/schools/alllessons', to: 'schools#alllessons'
  get '/schools/createlesson/:school_id', to: 'schools#createlesson'
  post '/schools/edit_lesson/:lesson_id', to: 'schools#edit_lesson'
  get '/schools/delete_lesson/:lesson_id', to: 'schools#delete_lesson'
  get 'update_booking_status/:id', to: 'learners#update_booking_status', as: :update_booking_status

  post '/learners/add_review/:lesson_id', to: 'learners#add_review'

  devise_for :users, :controllers => { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
   }

  authenticated :user, lambda {|user| user.admin? || user.school? } do
    get '/allusers', to: 'admin#allusers'
    get 'approve_user/:id', to: 'admin#approve_user', as: :approve_user
    get 'reject_user/:id', to: 'admin#reject_user', as: :reject_user
  end

  patch 'update', to: 'users#update', as: :update_profile

  get "up" => "rails/health#show", as: :rails_health_check

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/admin/allusers.html.erb
<div class="container-xl py-4">
  <h4>All <%= current_user.school? ? "Instructors" : "Users" %></h4>
  <% if @users.present? %>
    <div class="table-responsive">
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone number</th>
            <th>Address</th>
            <th>Picture</th>
            <% if current_user.school? %>
              <th>Fitness Certificate</th>
            <%end%>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td class="align-middle"><%= user.first_name %></td>
              <td class="align-middle"><%= user.last_name %></td>
              <td class="align-middle"><%= user.email %></td>
              <td class="align-middle"><%= user.phone_number %></td>
              <td class="align-middle"><%= user.address %></td>
              <td class="align-middle"><img src="<%=  user.picture.attached? ? url_for(user.picture) : "https://t3.ftcdn.net/jpg/03/58/90/78/360_F_358907879_Vdu96gF4XVhjCZxN2kCG0THTsSQi8IhT.jpg" %>" class="custom-image"  /></td>
              <% if user.instructor? %>
                <td class="align-middle"><img src="<%=  user.fitness_certificate.attached? ? url_for(user.fitness_certificate) : "" %>" class="custom-image" /></td>
              <%end%>
              <td class="align-middle">
                <% unless user.approved %>
                  <a href="<%= approve_user_path(user)%>" class="btn btn-primary" data-remote="true">Approve</a>
                <% else %>
                <a href="<%= reject_user_path(user)%>" class="btn btn-secondary" data-remote="true">Reject</a>
                <% end %>
              </td>
            </tr>
          <%end%>
        </tbody>
          
      </table>
    </div>
  <% else %>
    <div class="bg-white p-4 border rounded">No Users currently exists.</div>
  <% end %>
</div>