config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root to: "home#home"

  get '/learners/searchlocation', to: 'learners#searchlocation'
  get '/learners/allbookings', to: 'learners#allbookings'
  get '/learners/createbooking/:school_id', to: 'learners#createbooking'
  get '/instructors/allbookings', to: 'instructors#allbookings'
  get '/schools/allbookings', to: 'schools#allbookings'
  get '/schools/allinstructors', to: 'schools#allinstructors'
  get '/schools/alllessons', to: 'schools#alllessons'
  get '/schools/createlesson/:school_id', to: 'schools#createlesson'
  post '/schools/edit_lesson/:lesson_id', to: 'schools#edit_lesson'
  get '/schools/delete_lesson/:lesson_id', to: 'schools#delete_lesson'
  get 'update_booking_status/:id', to: 'learners#update_booking_status', as: :update_booking_status

  post '/learners/add_review/:lesson_id', to: 'learners#add_review'

  devise_for :users, :controllers => { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
   }

  authenticated :user, lambda {|user| user.admin? || user.school? } do
    get '/allusers', to: 'admin#allusers'
    get 'approve_user/:id', to: 'admin#approve_user', as: :approve_user
    get 'reject_user/:id', to: 'admin#reject_user', as: :reject_user
  end

  patch 'update', to: 'users#update', as: :update_profile

  get "up" => "rails/health#show", as: :rails_health_check

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/learners_controller.rb
class LearnersController < ApplicationController
  before_action :authenticate_user!

  def searchlocation
    @schools = User.school.search(params[:search]) if params[:search].present?
    @is_searchable = params[:search].present?
    respond_to do |format|
      format.js
      format.html
    end
  end

  def createbooking
    @booking = Booking.build(lesson_id: params[:lesson_id], school_id: params[:school_id])
    @booking.customer_id = current_user.id
    if @booking.save
      redirect_to request.referer, notice: "Booking created successfully"
    else
      redirect_to request.referer, alert: @booking.errors.full_messages.join
    end
  end

  def update_booking_status
    find_booking
    @booking.update!(status: params[:status])
    redirect_to request.referrer
  end

  def allbookings
    if current_user.user?
      @bookings = current_user.bookings
    elsif current_user.school?
      @bookings = current_user.school_bookings
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  def add_review
    if current_user.user?
      find_lesson
      @review = @lesson.reviews.build(rating: params[:rating], feedback: params[:feedback], booking_id: params[:booking_id], customer_id: current_user.id, school_id: params[:school_id])
      if @review.save!
        redirect_to request.referer, notice: "Thank you for your review."
      else
        redirect_to request.referer, alert: @review.errors.full_messages.join
      end
    else
      redirect_to request.referer, alert: "You can not perform this action!"
    end
  end

  private

    def find_user
      @user = User.find(params[:id])
    end

    def find_booking
      @booking = Booking.find(params[:id])
    end

    def find_lesson
      @lesson = Lesson.find(params[:lesson_id])
    end

    # def booking_params
    #   params.require(:booking).permit(:school_id, :lesson_id)
    # end
end

app/views/learners/_createbooking.html.erb
<div class="container-xl py-4 mw-700">
  <h4>Create Booking</h4>
  <% @schools.each do |school| %>
    <div class="d-flex align-items-center gap-3 border rounded p-3 bg-white">
      <%= form_with url: "/learners/createbooking/#{school.id}", method: :get, remote: true do |f| %>
        <div class="flex-grow-1">
          <h5><%= school.full_name.humanize %></h5>
          <div><%= school.address.humanize %></div>
          <div class="d-flex align-items-center gap-2 mt-1 mb-2">
            <img src="/star-full.svg" width="20" />
            <div class="fw-bold"><%= school.sum_of_ratings %></div>
            <div
              class="text-decoration-underline text-primary cursor-pointer"
              data-bs-toggle="modal"
              data-bs-target="#reviewsModal"
            >
              See Reviews
            </div>
          </div>
          <div
            class="d-flex align-items-center flex-wrap flex-sm-nowrap gap-2 mt-1 mb-2"
          >
            <%= select_tag :lesson_id, options_for_select(school.school_lessons.pluck(:title, :id)) , include_blank: "Select Lesson"  ,class: 'form-select mx-1 mx-sm-2 px-1 px-sm-3'%>
          </div>
        </div>
        <div>
          <input type="submit" value="Book" class="btn btn-primary" />
        </div>
      <% end %>
    </div>

  <!-- Reviews Modal -->
  <div
    class="modal fade"
    id="reviewsModal"
    tabindex="-1"
    aria-labelledby="reviewsModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="reviewsModalLabel">Reviews</h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <% if school.booking_reviews.present? %> 
            <% school.booking_reviews.each do |review| %>
            <div class="border-bottom mb-2 pb-1">
              <div class="d-flex align-items-center gap-2 mt-1 mb-1">
                <img src="/star-full.svg" width="20" />
                <div class="fw-bold"><%= review.rating.to_f %></div>
              </div>
              <%= review.feedback %>
              <div class="fw-bold mt-1"><%= review.customer.full_name.humanize %></div>
              <div class="d-flex align-items-center gap-2 mt-1">
                <div class="fw-bold">Lesson:</div>
                <div><%= review.lesson.title.humanize %></div>
              </div>
              <div class="d-flex align-items-center gap-2 mt-1">
                <div class="fw-bold">Instructor:</div>
                <div><%= review.lesson.instructor.full_name.humanize %></div>
              </div>
            </div>
            <% end %> 
          <% else %>
            <div>No reviews currently exists.</div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/learners/_review_modal.html.erb
<div
  class="modal fade"
  id="reviewModal"
  tabindex="-1"
  aria-labelledby="reviewModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="reviewModalLabel">
          How was your lesson and instructor
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <%= form_with url: "/learners/add_review/#{booking.lesson.id}", method: :post, remote: true do |f| %>
        <div class="modal-body">
          <div class="mb-3">
            <%= f.label :rating, 'Rate your instructor', class: 'form-label' %>
            <%= f.select :rating, options_for_select([['Select a rating', ''], ['Excellent', 5], ['Very Good', 4], ['Average', 3], ['Poor', 2], ['Terrible', 1]], selected: nil), {}, {class: 'star-rating form-control'} %>
          </div>
          <div class="mb-3">
            <%= f.label :feedback, 'Write your feedback', class: 'form-label' %>
            <%= f.text_area :feedback, rows: 3, class: 'form-control' %>
          </div>
          <%= f.hidden_field :booking_id, value: booking.id %>
          <%= f.hidden_field :school_id, value: booking.lesson.school.id %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          <%= f.submit 'Add Review', class: 'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/learners/allbookings.html.erb
<div class="container-xl py-4">
  <h4>All Bookings</h4>
  <% if @bookings.present? %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Lesson Name</th>
          <th>Insctructor Name</th>
          <th>School Name</th>
          <th>Status</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
        <tr>
          <td class="align-middle"><%= booking.lesson.title.humanize %></td>
          <td class="align-middle">
            <%= booking.lesson.instructor.full_name %>
          </td>
          <td class="align-middle"><%= booking.school.full_name %></td>
          <td class="align-middle">
            <% if booking.status == "completed" %>
              <span class="badge rounded-pill py-2 px-3 text-bg-success">
                Completed
              </span>
              <% elsif booking.status == "cancelled"%>
              <span class="badge rounded-pill py-2 px-3 text-bg-danger">
                Cancelled
              </span>
              <%elsif booking.status == "draft"%>
              <span class="badge rounded-pill py-2 px-3 text-bg-secondary">
                Draft
              </span>
              <%elsif booking.status == "confirmed"%>
              <span class="badge rounded-pill py-2 px-3 text-bg-primary">
                Confirmed
              </span>
            <%end%>
          </td>
          <td class="align-middle">
            <div class="d-flex align-items-center flex-wrap gap-2">
              <% if (booking.status == 'completed' && !booking.is_review_exist?) %>
                <a
                  class="btn btn-primary"
                  data-bs-toggle="modal"
                  data-bs-target="#reviewModal"
                >
                  Add your review
                </a>
                <%= render 'review_modal', booking: booking %>

              <% elsif (["draft", "confirmed"].include? booking.status) %>
                <a
                  href="<%= update_booking_status_path(booking.id, status: "cancelled")%>"
                  class="btn btn-danger"
                  data-remote="true"
                >
                  Cancel
              </a>
              <% end %>
            </div>
          </td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  
  <% else %>
    <div class="bg-white p-4 border rounded">No Booking currently exists.</div>
  <% end %>
</div>

app/views/learners/createbooking.html.erb
<div class="container-xl py-4 mw-700">
  <h4>Create Booking</h4>
  <%# @schools.each do |school| %>
  <form>
    <div class="d-flex align-items-center gap-3 border rounded p-3 bg-white">
      <div class="flex-grow-1">
        <h5>School Name</h5>
        <div>School Address</div>
        <div class="d-flex align-items-center gap-2 mt-1 mb-2">
          <img src="/star-full.svg" width="20" />
          <div class="fw-bold">4.5</div>
          <div
            class="text-decoration-underline text-primary cursor-pointer"
            data-bs-toggle="modal"
            data-bs-target="#reviewsModal"
          >
            See Reviews
          </div>
        </div>
        <div
          class="d-flex align-items-center flex-wrap flex-sm-nowrap gap-2 mt-1 mb-2"
        >
          <select class="form-select">
            <option disabled selected>Select Lesson</option>
            <option value="5">Lesson 1</option>
            <option value="4">Lesson 2</option>
          </select>
          <select class="form-select">
            <option disabled selected>Select Instructor</option>
            <option value="5">Instructor 1</option>
            <option value="4">Instructor 2</option>
          </select>
        </div>
      </div>
      <div>
        <input type="submit" value="Book" class="btn btn-primary" />
      </div>
    </div>
  </form>

  <!-- Reviews Modal -->
  <div
    class="modal fade"
    id="reviewsModal"
    tabindex="-1"
    aria-labelledby="reviewsModalLabel"
    aria-hidden="true"
  >
    <div class="modal-dialog modal-dialog-scrollable">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="reviewsModalLabel">Reviews</h1>
          <button
            type="button"
            class="btn-close"
            data-bs-dismiss="modal"
            aria-label="Close"
          ></button>
        </div>
        <div class="modal-body">
          <%# if @school.reviews.present? %> <%# @school.reviews.each do
          |review| %>
          <div class="border-bottom mb-2 pb-1">
            <div class="d-flex align-items-center gap-2 mt-1 mb-1">
              <img src="/star-full.svg" width="20" />
              <div class="fw-bold">4.5</div>
            </div>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry's standard dummy text
            ever since the 1500s
            <div class="fw-bold mt-1">Imran Hayat</div>
            <div class="d-flex align-items-center gap-2 mt-1">
              <div class="fw-bold">Lesson:</div>
              <div>Instructor Name</div>
            </div>
            <div class="d-flex align-items-center gap-2 mt-1">
              <div class="fw-bold">Instructor:</div>
              <div>Instructor Name</div>
            </div>
          </div>
          <%# end %> <%# else %>
          <div>No reviews currently exists.</div>
          <%# end %>
        </div>
      </div>
    </div>
  </div>
  <%# end %>
</div>

app/views/learners/searchlocation.html.erb
<div class="container my-5">
  <div class="py-5 px-3 px-lg-5 bg-white border rounded-3">
    <h1 class="text-body-emphasis text-center">Find driving schools</h1>
    <%= form_with url: learners_searchlocation_path, method: :get, remote: true, class: "mw-700 mx-auto d-flex flex-column justify-content-center align-items-start gap-3 mt-4" do |f| %>

        <label class="form-label h4 mb-0 fw-normal">Search by location</label>
        <%= f.text_field :search, value: params[:search], placeholder: "Enter location", class: "form-control form-control-lg", required: true %>

        <%= f.submit "Search", class: "btn btn-primary btn-lg" %>
    <% end %>

    <% if @schools.present? %>
      <%= render 'createbooking' %>
    <% else %>
      <p> No Results Found! </p>
    <% end %>
  </div>
</div>