config/routes.rb
Rails.application.routes.draw do
  # devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  root to: "home#home"

  get '/learners/searchlocation', to: 'learners#searchlocation'
  get '/learners/allbookings', to: 'learners#allbookings'
  get '/learners/createbooking/:school_id', to: 'learners#createbooking'
  get '/instructors/allbookings', to: 'instructors#allbookings'
  get '/schools/allbookings', to: 'schools#allbookings'
  get '/schools/allinstructors', to: 'schools#allinstructors'
  get '/schools/alllessons', to: 'schools#alllessons'
  get '/schools/createlesson/:school_id', to: 'schools#createlesson'
  post '/schools/edit_lesson/:lesson_id', to: 'schools#edit_lesson'
  get '/schools/delete_lesson/:lesson_id', to: 'schools#delete_lesson'
  get 'update_booking_status/:id', to: 'learners#update_booking_status', as: :update_booking_status

  post '/learners/add_review/:lesson_id', to: 'learners#add_review'

  devise_for :users, :controllers => { 
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
   }

  authenticated :user, lambda {|user| user.admin? || user.school? } do
    get '/allusers', to: 'admin#allusers'
    get 'approve_user/:id', to: 'admin#approve_user', as: :approve_user
    get 'reject_user/:id', to: 'admin#reject_user', as: :reject_user
  end

  patch 'update', to: 'users#update', as: :update_profile

  get "up" => "rails/health#show", as: :rails_health_check

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :authenticate_user!

  def alllessons
    @lessons = current_user.school_lessons
    respond_to do |format|
      format.js
      format.html
    end
  end

  def createlesson
    @lesson = Lesson.build(title: params[:title], description: params[:description], instructor_id: params[:instructor_id])
    @lesson.school_id = current_user.id
    if @lesson.save!
        redirect_to request.referer, notice: "Lesson created successfully"
    else
        redirect_to request.referer, alert: @lesson.errors.full_messages.join
    end
  end

  def edit_lesson
    find_lesson
    if @lesson.update!(title: params[:title], description: params[:description], instructor_id: params[:instructor_id])
      redirect_to request.referer, notice: "Lesson updated successfully"
    else
      redirect_to request.referer, alert: @lesson.errors.full_messages.join
    end
  end

  def delete_lesson
    find_lesson
    if @lesson.destroy
      redirect_to request.referer, notice: "Lesson deleted successfully"
    else
      redirect_to request.referer, alert: @lesson.errors.full_messages.join
    end
  end

  def allinstructors
  end

  def allbookings
    if current_user.user?
      @bookings = current_user.bookings
    elsif current_user.school?
      @bookings = current_user.school_bookings
    end
    respond_to do |format|
      format.js
      format.html
    end
  end

  private

    def find_lesson
      @lesson = current_user.school_lessons.find(params[:lesson_id])
    end

    # def lesson_params
    #   params.require(:lesson).permit(:title, :description, :school_id, :instructor_id)
    # end

end

app/views/schools/_createlesson.html.erb
<div
  class="modal fade"
  id="createLessonModal"
  tabindex="-1"
  aria-labelledby="createLessonModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="createLessonModalLabel">
          Add a new lesson
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <%= form_with url: "/schools/createlesson/#{current_user.id}", method: :get, remote: true do |f| %>
        <div class="modal-body">
          <div class="d-flex align-items-center">
            <main class="border form-signin w-100 mx-auto my-3 p-4 bg-white rounded">
                <div class="mb-3">
                  <%= f.label :title, class:"form-label" %>
                  <%= f.text_field :title, class:"form-control", required: true %>
                </div> 
                <div class="mb-3">
                  <%= f.label :description, class:"form-label" %>
                  <%= f.text_area :description, class:"form-control" %>
                </div>

                <div class="mb-3">
                  <%= select_tag :instructor_id, options_for_select(User.instructor.pluck(:first_name, :id)) , include_blank: "Assign Instructor"  ,class: 'form-select mx-1 mx-sm-2 px-1 px-sm-3'%>
                </div>             
            </main>
          </div>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Cancel
          </button>
          <%= f.submit "Create", class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/schools/_updatelesson.html.erb
<div
  class="modal fade"
  id="updateLessonModal"
  tabindex="-1"
  aria-labelledby="updateLessonModalLabel"
  aria-hidden="true"
>
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="updateLessonModalLabel">
          Update lesson
        </h1>
        <button
          type="button"
          class="btn-close"
          data-bs-dismiss="modal"
          aria-label="Close"
        ></button>
      </div>
      <%= form_with(url: "/schools/edit_lesson/#{lesson.id}", method: :post, class: "mw-700 mx-auto d-flex flex-column gap-3 mt-4") do |f| %>
        <div class="modal-body">
          <div class="d-flex align-items-center">
            <main class="border form-signin w-100 mx-auto my-3 p-4 bg-white rounded">
                <div class="mb-3">
                  <%= f.label :title, class:"form-label" %>
                  <%= f.text_field :title, class:"form-control", value: lesson.title, required: true %>
                </div> 
                <div class="mb-3">
                  <%= f.label :description, class:"form-label" %>
                  <%= f.text_area :description, class:"form-control", value: lesson.description %>
                </div>

                <div class="mb-3">
                  <%= select_tag :instructor_id, options_for_select(User.instructor.pluck(:first_name, :id), lesson.instructor_id), include_blank: "Assign Instructor", class: 'form-select mx-1 mx-sm-2 px-1 px-sm-3' %>
                </div>             
            </main>
          </div>
        </div>
        <div class="modal-footer">
          <button
            type="button"
            class="btn btn-secondary"
            data-bs-dismiss="modal"
          >
            Cancel
          </button>
          <%= f.submit "Update", class:'btn btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/schools/allbookings.html.erb
<div class="container-xl py-4">
  <h4>All Bookings</h4>
  <% if @bookings.present? %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>User Name</th>
          <th>Lesson Name</th>
          <th>Insctructor Name</th>
          <th>Status</th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
        <tr>
          <td class="align-middle">
            <%= booking.customer.first_name %><%= booking.customer.last_name %>
          </td>
          <td class="align-middle"><%= booking.lesson.title&.humanize %></td>
          <td class="align-middle">
            <%= booking.lesson.instructor.full_name %>
          </td>
          <td class="align-middle">
            <% if booking.status == "completed" %>
            <span class="badge rounded-pill py-2 px-3 text-bg-success">
              Completed
            </span>
            <% elsif booking.status == "cancelled"%>
            <span class="badge rounded-pill py-2 px-3 text-bg-danger">
              Cancelled
            </span>
            <%elsif booking.status == "draft"%>
            <span class="badge rounded-pill py-2 px-3 text-bg-secondary">
              Draft
            </span>
            <%elsif booking.status == "confirmed"%>
            <span class="badge rounded-pill py-2 px-3 text-bg-primary">
              Confirmed
            </span>
            <%end%>
          </td>
        </tr>
        <%end%>
      </tbody>
    </table>
  </div>
  <% else %>
  <div class="bg-white p-4 border rounded">No Booking currently exists.</div>
  <% end %>
</div>

app/views/schools/allinstructors.html.erb
<div class="container-xl py-4">
  <h4>All Instructors</h4>
  <%# if @instructors.present? %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Phone number</th>
          <th>Address</th>
          <th>Picture</th>
          <th>Fitness Certificate</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <%# @instructors.each do |instructor| %>
          <tr>
            <td class="align-middle"><%#= instructor.first_name %></td>
            <td class="align-middle"><%#= instructor.last_name %></td>
            <td class="align-middle"><%#= instructor.email %></td>
            <td class="align-middle"><%#= instructor.phone_number %></td>
            <td class="align-middle"><%#= instructor.address %></td>
            <td class="align-middle"><img src="<%#=  url_for(instructor.picture) %>" class="custom-image"  /></td>
            <td class="align-middle"><img src="<%#=  url_for(instructor.fitness_certificate) %>" class="custom-image" /></td>
            <td class="align-middle">
              <%# unless instructor.approved %>
                <a href="<%#= approve_instructor_path(instructor)%>" class="btn btn-primary" data-remote="true">Approve</a>
              <%# else %>
              <a href="<%#= reject_instructor_path(instructor)%>" class="btn btn-secondary" data-remote="true">Reject</a>
              <%# end %>
            </td>
          </tr>
        <%#end%>
      </tbody>
        
    </table>
  </div>
  <%# else %>
    <div class="bg-white p-4 border rounded">No Instructors currently exists.</div>
  <%# end %>
</div>

app/views/schools/alllessons.html.erb
<div class="container-xl py-4">
  <div class="d-flex align-items-center justify-content-between mb-3">
    <h4 class="mb-0">All Lessons</h4>
    <a data-bs-toggle="modal" data-bs-target="#createLessonModal" class="btn btn-primary">Add New Lesson</a>
  </div>
  <% if @lessons.present? %>
  <div class="table-responsive">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th>Lesson Name</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @lessons.each do |lesson| %>
        <tr>
          <td class="align-middle"><%= lesson.title&.humanize %></td>
          <td class="align-middle">
            <div class="d-flex align-items-center flex-wrap gap-2">
              <a
                data-bs-toggle="modal" data-bs-target="#updateLessonModal"
                class="btn btn-primary"
              >
                Edit
              </a>
              <a
                href="<%= "/schools/delete_lesson/#{lesson.id}"%>"
                data-remote="true"
                class="btn btn-danger"
              >
                Delete
              </a>
            </div>
          </td>
        </tr>
        <%= render 'updatelesson', lesson: lesson %>
        <%end%>
      </tbody>
    </table>
  </div>
  <% else %>
  <div class="bg-white p-4 border rounded">No lesson currently exists.</div>
  <% end %>
</div>
<%= render 'createlesson' %>